Files already downloaded and verified
Files already downloaded and verified
CometLogger will be initialized in online mode
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    train_log_file_path=option.train_log_file_path
  File "train.py", line 72, in main
    trainer.fit(model, train_dataloader, validation_dataloader)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 474, in fit
    self.setup_trainer(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 421, in setup_trainer
    self.logger.log_hyperparams(model.hparams_initial)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 40, in wrapped_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/comet.py", line 233, in log_hyperparams
    self.experiment.log_parameters(params)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 41, in experiment
    return get_experiment() or DummyExperiment()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 40, in wrapped_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 39, in get_experiment
    return fn(self)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/comet.py", line 203, in experiment
    **self._kwargs,
  File "/opt/conda/lib/python3.7/site-packages/comet_ml/__init__.py", line 293, in __init__
    auto_histogram_activation_logging=auto_histogram_activation_logging,
  File "/opt/conda/lib/python3.7/site-packages/comet_ml/experiment.py", line 502, in __init__
    raise ImportError(msg)
ImportError: You must import Comet before these modules: torch, tensorboard
CometLogger will be initialized in online mode
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "/workspace/train.py", line 86, in <module>
    train_log_file_path=option.train_log_file_path
  File "/workspace/train.py", line 72, in main
    trainer.fit(model, train_dataloader, validation_dataloader)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    self.pre_dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 539, in pre_dispatch
    self.accelerator.pre_dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 84, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 233, in pre_dispatch
    self.init_ddp_connection(self.global_rank, self.world_size)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 216, in init_ddp_connection
    torch_distrib.init_process_group(self.torch_distributed_backend, rank=global_rank, world_size=world_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 423, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: connect() timed out.
